# Generated by Django 3.1.2 on 2020-10-18 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="url",
            options={"verbose_name_plural": "url"},
        ),
        migrations.AddField(
            model_name="url",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
