# Generated by Django 3.1.2 on 2020-10-20 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0007_auto_20201020_1216"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homepage", "0002_auto_20201018_2127"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Url",
            new_name="Link",
        ),
    ]
