# Generated by Django 3.1.2 on 2020-10-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0003_auto_20201020_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="confirm",
            field=models.BooleanField(default=False),
        ),
    ]
