# Generated by Django 3.1.2 on 2020-10-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0007_auto_20201023_1525"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrcode",
            options={"verbose_name_plural": "qrcode"},
        ),
    ]
