# Generated by Django 3.1.2 on 2020-10-23 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0008_auto_20201023_1530"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="id",
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="link",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="homepage.link",
            ),
        ),
    ]
