# Generated by Django 3.1.2 on 2020-10-23 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0009_auto_20201023_1535"),
    ]

    operations = [
        migrations.CreateModel(
            name="UTM",
            fields=[
                (
                    "link",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="homepage.link",
                    ),
                ),
                ("utm_source", models.TextField(blank=True, null=True)),
                ("utm_medium", models.TextField(blank=True, null=True)),
                ("utm_campaign", models.TextField(blank=True, null=True)),
                ("utm_term", models.TextField(blank=True, null=True)),
                ("utm_content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
