# Generated by Django 3.1.2 on 2020-10-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0013_link_utm_original"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="utm_original",
        ),
    ]
