# Generated by Django 3.1.2 on 2020-10-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0016_auto_20201024_1829"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="marker",
            field=models.BooleanField(default=True),
        ),
    ]
