# Generated by Django 3.1.2 on 2020-10-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0017_link_marker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["-id"], "verbose_name_plural": "link"},
        ),
        migrations.AlterField(
            model_name="link",
            name="marker",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="link",
            name="shortcut",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
