# Generated by Django 3.1.3 on 2020-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0019_auto_20201029_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="shortcut",
            field=models.URLField(
                blank=True, editable=False, max_length=300, null=True
            ),
        ),
    ]
