# Generated by Django 3.1.3 on 2020-11-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0020_auto_20201107_1257"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="shortcut",
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
