version: 2.1

workflows:
  main:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout

      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv-dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/

      - run:
          name: Performing Tests
          command: |
            make test

