version: 2.1

workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - dockerhub-creds

jobs:
  build-and-test:
    environment:
      ENV_FOR_DYNACONF: ci
      PYTHONPATH: src

    docker:
      - image: circleci/python:3.8.5-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv-dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/

      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.9.1.jar -log tests/functional/artifactcs/selenium.log
          background: true


      - run:
          name: Performing Tests
          command: |
            make test