version: 2.1

orbs:
  python: circleci/python@0.2.1

workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - dockerhub-creds

jobs:
  build-and-test:
    steps:
      - docker:
          - image: circleci/python:3.8.5-browsers
            auth:
              username: $DOCKERHUB_USERNAME
              password: $DOCKERHUB_PASSWORD

      - checkout

      - restore_cache:
          keys:
            - cc-venv-{{ checksum "Pipfile.lock" }}
      - run:
          name: Setting up virtualenv
          command: |
            sudo pip install pipenv
            make venv-dev
      - save_cache:
          key: cc-venv-{{ checksum "Pipfile.lock" }}
          paths:
            - ./.venv/

      - run:
          name: Performing Tests
          command: |
            make test

