default:
  ALLOWED_HOSTS: []
  PORT: 0
  DATABASE_URL: ''
  DEBUG: false
  SECRET_KEY: ""
  SENTRY_DSN: ""
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: ""
  SOCIAL_AUTH_VK_OAUTH2_KEY: ""
  SOCIAL_AUTH_VK_OAUTH2_SECRET: ""

development:
  PORT: 8000
  DATABASE_URL: ''
  DEBUG: true
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: 'http'

heroku:
  ALLOWED_HOSTS:
    - 'urlcutt.herokuapp.com'
  DEBUG: false
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: 'https'