# Generated by Django 3.1.2 on 2020-10-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_auto_20201018_2127"),
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_adress", models.GenericIPAddressField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "url",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.url",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Url",
        ),
    ]
