# Generated by Django 3.1.2 on 2020-10-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0003_auto_20201018_2133"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="os",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="hit",
            name="browser",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
