# Generated by Django 3.1.2 on 2020-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0004_auto_20201019_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
