# Generated by Django 3.1.2 on 2020-10-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0005_hit_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
