# Generated by Django 3.1.2 on 2020-10-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0006_hit_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hit",
            old_name="ip_adress",
            new_name="ip_address",
        ),
    ]
