# Generated by Django 3.1.2 on 2020-10-21 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_auto_20201020_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 21, 8, 27, 19, 864308), null=True),
        ),
    ]
