# Generated by Django 3.1.2 on 2020-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0010_auto_20201021_1135"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hit",
            options={"ordering": ["-time"]},
        ),
    ]
