# Generated by Django 3.1.2 on 2020-10-23 20:03

import django.db.models.deletion
import storages.backends.s3boto3
from django.db import migrations, models

import applications.homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0012_auto_20201023_2003"),
        ("statistics", "0011_auto_20201021_2231"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "link",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="homepage.link",
                    ),
                ),
                (
                    "original",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=storages.backends.s3boto3.S3Boto3Storage(),
                        upload_to=applications.homepage.models.upload_to,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "qrcode",
            },
        ),
        migrations.CreateModel(
            name="UTM",
            fields=[
                (
                    "link",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="homepage.link",
                    ),
                ),
                ("utm_source", models.CharField(blank=True, max_length=200, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
