# Generated by Django 3.1.2 on 2020-11-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0012_qrcode_utm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hit",
            old_name="url",
            new_name="link",
        ),
    ]
