# Generated by Django 3.1.3 on 2020-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0014_auto_20201107_1254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utm",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="utm",
            name="utm_content",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="utm",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="utm",
            name="utm_source",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="utm",
            name="utm_term",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
